site_name: yangzhang's Site
site_url: https://yangzhang.site/


nav:
  - Blog:
    - Blog/index.md
    - Blog/站内导航.md
    - Jupyter:
      - 介绍: Blog/jupyter/jupyter1.md
      - 基础使用: Blog/jupyter/jupyter2.md
      - 远程服务: Blog/jupyter/jupyter3.md
      - 进阶使用: Blog/jupyter/jupyter4.md
  - SomeMath:
    - SomeMath/index.md
    - SomeMath/一道有理函数不定积分.md
    - SomeMath/泰勒展开/泰勒展开.md
    - SomeMath/线性齐次差分方程.md
  - Tags: tags.md
  - About:
    - About/index.md

# [UI]
## [top]
theme:
  logo: assets/images/summation.png
  name: material
  palette: 
    - scheme: default # 日间模式
      primary: indigo # 上方的
      accent: orange # 链接等可交互元件的高亮色
      toggle:
        icon: material/weather-night # 图标
        name: 切换至夜间模式 # 鼠标悬浮提示
    - scheme: slate # 夜间模式
      primary: indigo
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: 切换至日间模式
  features:
    - navigation.tabs # 使用Tab来进行分类
    - navigation.top # 返回顶部的按钮 在上滑时出现
    - navigation.indexes # Tab会有一个index.md 而不是在打开Tab时打开第一篇文章
    - navigation.expand # 打开Tab时左侧目录全部展开
    - search.suggest # 搜索输入一些字母时推荐补全整个单词
    - search.highlight # 搜索出的文章关键词加入高亮
  language: zh # 一些提示性的文字会变成中文
  icon:
    repo: fontawesome/brands/github

edit_uri: edit/main/docs # 编辑按钮跳转的链接

## [top-right corner]
repo_url: https://github.com/AIboy996/AIboy996.GitHub.io # 右上角点击跳转的链接
repo_name: AIboy996.github.io # 右上角的名字
## [bottom-left corner]
copyright: Copyright &copy; 2022 yangzhang # 左下角的版权声明
## [bottom-right corner]
extra:
  social: # icons
    - icon: fontawesome/brands/github
      link: https://github.com/AIboy996
      name: GitHub | AIboy996
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/85735334
      name: BiliBili | 豆汁泡纳豆



# [Extensions]
plugins:
  - search: # 现在还不支持中文搜索 支持之后可以设置语言
    # insider已经支持中文的分词搜索了 https://squidfunk.github.io/mkdocs-material/blog/2022/chinese-search-support/
      lang:
        - en
  - tags:
      tags_file: tags.md
  
  
  # 给单篇文章添加标签 https://squidfunk.github.io/mkdocs-material/setup/setting-up-tags/?h=tags
markdown_extensions:
  - pymdownx.arithmatex: # latex支持
      generic: true
  - toc:
      permalink: true # 固定标题位置为当前位置
  - pymdownx.highlight: # 代码块高亮
      linenums: true # 显示行号
      auto_title: true # 显示编程语言名称
  - pymdownx.superfences # 代码块高亮插件
  # - meta # 支持Markdown文件上方自定义标题标签等

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML
