site_name: yangzhang's Site
site_url: https://yangzhang.site/
site_author: yangzhang
site_description: yangzhang的个人网站
nav:
  - About:
    - About/index.md
    - About/about.md
    - About/友链.md
  - Blog:
    - Blog/index.md
    - 墙和梯子:
      - Blog/GFW/简介.md
    - mkdocs:
      - Blog/mkdocs/理论.md
      - Blog/mkdocs/实践.md
    - Jupyter:
      - 介绍: Blog/jupyter/jupyter1.md
      - 基础使用: Blog/jupyter/jupyter2.md
      - 远程服务: Blog/jupyter/jupyter3.md
      - 进阶使用: Blog/jupyter/jupyter4.md
    - SAS:
      - SAS的基本操作: Blog/SAS/SAS的基本操作.md
      - SAS的统计应用: Blog/SAS/SAS的统计应用.md
  - Python:
    - Python/index.md
    - Python/python前置知识.md
    - 基础语法:
      - Python/基础语法/python基础语法1.md
      - Python/基础语法/python基础语法2.md
    - 进阶语法:
      - Python/进阶语法/python进阶语法1.md
      - Python/进阶语法/python进阶语法2.md
      - Python/进阶语法/python进阶语法3.md
    - 标准库:
      - Python/标准库/OS.md
    - 第三方库:
      - Python/第三方库/numpy.md
  - SomeMath:
    - SomeMath/index.md
    - 杂题:
        - SomeMath/一道复杂极限.md
        - SomeMath/一道有理函数不定积分.md
    - SomeMath/泰勒展开/泰勒展开.md
    - SomeMath/线性齐次差分方程.md
    - Montmort:
        - SomeMath/Montmort问题（一）.md
    - SomeMath/双曲函数.md
  - Tags: tags.md
  - Playground: playground.md

theme:
  name: material
  custom_dir: overrides
  logo: assets/images/summation.png
  palette: 
    - scheme: default # 日间模式
      primary: indigo # 上方的
      accent: orange # 链接等可交互元件的高亮色
      toggle:
        icon: material/weather-night # 图标
        name: 切换至夜间模式 # 鼠标悬浮提示
    - scheme: slate # 夜间模式
      primary: indigo
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: 切换至日间模式
  features:
    - content.code.annotate # 代码块内的注释
    - navigation.tabs # 使用Tab来进行分类
    - navigation.top # 返回顶部的按钮 在上滑时出现
    - navigation.indexes # Tab会有一个index.md 而不是在打开Tab时打开第一篇文章
    - navigation.expand # 打开Tab时左侧目录全部展开
    - search.suggest # 搜索输入一些字母时推荐补全整个单词
    - search.highlight # 搜索出的文章关键词加入高亮
    - content.code.copy # 代码内容给一个复制按钮
  language: zh # 一些提示性的文字会变成中文
  icon:
    repo: fontawesome/brands/github

edit_uri: ""  # 编辑按钮跳转的链接

repo_name: AIboy996.github.io
repo_url: https://github.com/AIboy996/AIboy996.github.io
copyright: Copyright &copy; 2022 yangzhang # 左下角的版权声明

extra:
  analytics:
    provider: google
    property: G-8R9VRSN3S0
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target="_blank" rel="noopener">feedback form</a>.
  social: # icons
    - icon: fontawesome/brands/github
      link: https://github.com/AIboy996
      name: GitHub | AIboy996
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/85735334
      name: BiliBili | 豆汁泡纳豆

plugins:
  - search:
      prebuild_index: true
      lang:
        - en
        # 日语搜索汉字
        - ja
  - tags:
      tags_file: tags.md
  
markdown_extensions:
  - md_in_html
  - attr_list # 给图片后面添加{width="300"}设置大小
  - pymdownx.arithmatex: # latex支持
      generic: true
  - footnotes
  - toc:
      permalink: true # 固定标题位置为当前位置
      toc_depth: 3
  - pymdownx.highlight: # 代码块高亮
      linenums: true # 显示行号
      auto_title: true # 显示编程语言名称
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
        custom_fences:
            - name: mermaid
              class: mermaid
              format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true 
  - meta # 支持Markdown文件上方自定义标题标签等

extra_javascript:
  # 百度的页面访问统计
  - assets/js/baidu.js
  # 数学公式格式支持
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML
  # 鼠标点击特效
  - https://cdn.jsdelivr.net/gh/TRHX/CDN-for-itrhx.com@3.0.8/js/maodian.js
