site_name: yangzhang's Site
site_url: https://yangzhang.site/
site_author: Yang Zhang
site_description: 张杨的个人网站
nav:
  - About:
    - About/index.md
    - About/about.md
    - About/devices.md
    - 正式的简历: About/resume.html
    - About/hobby.md
    - About/links.md
  - Note:
    - Note/index.md
    - Note/software.md
    - Docker:
      - Note/Docker/docker_intro.md
      - Note/Docker/docker_basic.md
      - Note/Docker/docker_senior.md
    - Git:
      - Note/Git/git.md
      - Note/Git/git_server.md
    - GreatFirewall:
      - Note/GFW/intro.md
      - Note/GFW/client.md
      - Note/GFW/server.md
    - Jupyter:
      - 介绍: Note/jupyter/jupyter1.md
      - 基础使用: Note/jupyter/jupyter2.md
      - 远程服务: Note/jupyter/jupyter3.md
      - 进阶使用: Note/jupyter/jupyter4.md
    - LaTeX:
      - Note/latex/basic_latex.md
    - Linux & Shell:
      - Note/Shell/linux.md
      - Note/Shell/man.md
      - Note/Shell/ssh.md
    - ManimGL:
      - Note/manim/hello.md
    - MkDocs:
      - Note/mkdocs/theory.md
      - Note/mkdocs/practice.md
      - Note/mkdocs/best_practices.md
      - Note/mkdocs/about_math.md
    - SAS:
      - SAS的基本操作: Note/SAS/SAS_basic.md
      - SAS的统计应用: Note/SAS/SAS_application.md
  - Blog:
    - Blog/index.md
    - 2019:
      - Blog/2019/2019_summary.md
    - 2020:
      - Blog/2020/2020_summary.md
    - 2022:
      - Blog/2022/2022_summary.md
    - 2023:
      - Blog/2023/intern.md
      - Blog/2023/curriculum.md
      - Blog/2023/GEE.md
      - Blog/2023/music.md
      - Blog/2023/intern2.md
      - Blog/2023/thesis.md
      - Blog/2023/travel_to_japan.md
      - Blog/2023/recall_high_school_math.md
      - Blog/2023/graduation_pics.md
      - Blog/2023/name.md
      - Blog/2023/bloom.md
      - Blog/2023/2023_summary.md
    - 2024:
      - Blog/2024/otaku.md
      - Blog/2024/winter.md
      - Blog/2024/sakura.md
      - Blog/2024/new_blog.md
      - Blog/2024/envelope.md
      - Blog/2024/no_argmax.md
  - Python:
    - Python/index.md
    - Python/pre_python.md
    - Python/command_line.md
    - Python/script.md
    - 基础语法:
      - Python/BasicSyntax/builtin_class.md
      - Python/BasicSyntax/builtin_keyword.md
    - 高级语法:
      - Python/SeniorSyntax/functional_programming.md
      - Python/SeniorSyntax/OOP.md
    - 标准库:
      - Python/StandardLibrary/os.md
      - Python/StandardLibrary/re.md
      - Python/StandardLibrary/time.md
    - 第三方库:
      - Python/ThirdPartyLibrary/package_management.md
      - Python/ThirdPartyLibrary/DIY.md
      - numpy:
        - Python/ThirdPartyLibrary/numpy/index.md
        - Python/ThirdPartyLibrary/numpy/ndarray.md
      - matplotlib:
        - Python/ThirdPartyLibrary/matplotlib/index.md
        - Python/ThirdPartyLibrary/matplotlib/plt.md
        - Python/ThirdPartyLibrary/matplotlib/subplots.md
      - pandas:
        - Python/ThirdPartyLibrary/pandas/index.md
        - Python/ThirdPartyLibrary/pandas/dataframe.md
      - pytorch:
        - Python/ThirdPartyLibrary/pytorch/index.md
        - Python/ThirdPartyLibrary/pytorch/quick_start.md
        - Python/ThirdPartyLibrary/pytorch/tensor.md
        - Python/ThirdPartyLibrary/pytorch/data.md
        - Python/ThirdPartyLibrary/pytorch/model.md
        - Python/ThirdPartyLibrary/pytorch/optimizer.md
        - Python/ThirdPartyLibrary/pytorch/multi_gpu.md
    - 应用案例（MISC）:
      - Python/Example/email.md
    - 应用案例（爬虫）:
      - Python/Example/Spider/national_FDA.md
      - Python/Example/Spider/local_FDA.md
    - 应用案例（微软三件套）:
      - Python/Example/Excel/csv2xlsx.md
  - Project:
    - Project/index.md
    - Project/qrq.md
    - Project/pymd.md
    - Project/plt-gallery.md
    - Project/high_school_math.md
    - Project/AirPrint-with-Python.md
    - Project/Course-Selection-System.md
  - Statistics:
    - Statistics/index.md
    - 基础课:
      - Statistics/basic/Calculus.md
      - Statistics/basic/Linear_Algebra.md
      - Statistics/basic/Operations_Research.md
      - Statistics/basic/Probability_Theory_and_Mathematical_Statistics.md
      - Statistics/basic/Statistical_Software.md
    - 专业课:
      - Statistics/specialized/Statistical_Inference.md
      - Statistics/specialized/Regression_Analysis.md
      - Statistics/specialized/Time_Series_Analysis.md
      - Statistics/specialized/Sampling.md
      - Statistics/specialized/Multivariate_Analysis.md
      - Statistics/specialized/Stochastic_Process.md
      - Statistics/specialized/Categorical_Data_Analysis.md
      - Statistics/specialized/Nonparametric_Statistics.md
    - 选修课:
      - Statistics/elective/Computational_Statistics.md
      - Statistics/elective/Data_Mining.md
      - Statistics/elective/Algorithm.md
      - Statistics/elective/DSPython.md
      - Statistics/elective/Database.md
      - Statistics/elective/Pattern_Recognition_and_Machine_Learning.md
      - Statistics/elective/SeniorPython.md
      - Statistics/elective/OpenMMLab.md
    - 研究生课:
      - Statistics/postgrad/Probability_Theory.md
      - Statistics/postgrad/Convex_Optimization.md
      - Statistics/postgrad/Numerical_Analysis.md
      - Statistics/postgrad/Time_Series.md
      - Statistics/postgrad/Deep_Learning.md
      - Statistics/postgrad/Reinforcement_Learning.md
      - Statistics/postgrad/journal_club.md
  - SomeMath:
    - SomeMath/index.md
    - 实分析:
      - SomeMath/real/rational_numbers_countable.md
      - SomeMath/real/taylor_expand/taylor_expand.md
      - SomeMath/real/hyperbolic_function.md
      - SomeMath/real/a_limit.md
      - SomeMath/real/derivatives.md
      - SomeMath/real/gamma_func.md
    - 复分析:
      - SomeMath/complex/why_complex.md
      - SomeMath/complex/constructible_number.md
    - 代数:
      - SomeMath/algebra/linear_differential_equation.md
    - 概率论:
      - SomeMath/prob/Montmort.md
      - SomeMath/prob/conditional_expectation.md
  - Tags: Tags/index.md
  - Playground: Playground/index.md

theme:
  name: material
  custom_dir: overrides
  logo: assets/images/summation.png
  palette:  # 一周七天，六种颜色
    - scheme: sun
      primary: deep purple
      accent: orange
    - scheme: mon
      primary: grey
      accent: orange
    - scheme: tues
      primary: blue grey
      accent: orange
    - scheme: wed
      primary: teal
      accent: orange
    - scheme: thur
      primary: indigo
      accent: orange
    - scheme: fri
      primary: pink
      accent: orange
    - scheme: sat
      primary: deep purple
      accent: orange

  features:
    - content.code.annotate # 代码块内的注释
    - navigation.tabs # 使用Tab来进行分类
    - navigation.top # 返回顶部的按钮 在上滑时出现
    - navigation.indexes # Tab会有一个index.md 而不是在打开Tab时打开第一篇文章
    # - navigation.expand # 打开Tab时左侧目录全部展开
    - search.suggest # 搜索输入一些字母时推荐补全整个单词
    - search.highlight # 搜索出的文章关键词加入高亮
    - content.code.copy # 代码内容给一个复制按钮
    # - announce.dismiss # 公告标记为已读
  language: zh # 一些提示性的文字会变成中文
  icon:
    repo: fontawesome/brands/github

repo_name: AIboy996.github.io
repo_url: https://github.com/AIboy996/AIboy996.github.io
copyright: "<a href='https://github.com/AIboy996/AIboy996.GitHub.io/blob/main/LICENSE'>&copy; 2022-2024 Yang Zhang</a>" # 左下角的版权声明

extra:
  consent:
    title: Cookie consent
    description: >- 
      I am using cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of posts and whether users can find what 
      they're searching for. With your consent, all of this are helping me to
      make my site better.
  analytics:
    provider: google
    property: G-8R9VRSN3S0
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help me improve this page by using the <a href="https://github.com/AIboy996/AIboy996.GitHub.io/issues/new/?title=[Feedback]+{title}+-+{url}" target="_blank" rel="noopener">feedback form</a>.
  social: # icons
    - icon: fontawesome/brands/github
      link: https://github.com/AIboy996
      name: GitHub | AIboy996
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/85735334
      name: BiliBili | 豆汁泡纳豆
    - icon: fontawesome/solid/list-check
      link: https://bangumi.tv/anime/list/759154/do
      name: bangumi追番列表
    - icon: fontawesome/solid/rss
      link: https://yangzhang.site/feed_rss_updated.xml
      name: RSS

plugins:
  - i18n:
      docs_structure: suffix
      languages:
        - locale: zh
          default: true
          name: 简体中文
          build: true
        - locale: en
          name: English
          build: true
          nav_translations:
              正式的简历: Resume
  ## jupyter文件支持
  ########## 暂时移除此功能
  #- mkdocs-jupyter
  - mkdocs-video:
      is_video: true
      video_muted: false
      video_controls: true
      video_autoplay: false
      css_style:
        width: "80%"
        display: block;
        margin-left: auto;
        margin-right: auto;
  - tags
  ## 图片放大插件
  - glightbox:
      effect: zoom
      zoomable: true
      draggable: true
      skip_classes:
        - nonzoom
  ## 文章日期插件
  - git-revision-date-localized:
      timezone: Asia/Irkutsk
      enable_creation_date: true
      type: iso_datetime
  ## 搜索插件
  - search:
      lang:
        - en
        # 日语搜索汉字
        - ja
        - zh
  - minify:
      minify_html: true
  - rss

markdown_extensions:
  - md_in_html
  - attr_list # 给图片后面添加{width="300"}设置大小
  # - pymdownx.arithmatex # 更换渲染的方式，不依赖此插件，直接使用MathJax渲染
  - footnotes
  - toc:
      permalink: true # 固定标题位置为当前位置
      toc_depth: 3
  - pymdownx.highlight: # 代码块高亮
      # auto_title: true # 显示编程语言名称
  - admonition
  - pymdownx.details
  - pymdownx.tasklist
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.superfences:
        custom_fences:
            - name: mermaid
              class: mermaid
              format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true 
  - meta # 支持Markdown文件上方自定义标题标签等

extra_css:
  - assets/stylesheets/extra.css
  - assets/stylesheets/termynal.css

extra_javascript:
  # 百度的页面访问统计【暂时移除百度的访问统计（加载实在是有点慢】
  # - assets/js/baidu.js
  
  # 随着星期几改变主题颜色
  - assets/javascripts/color.js

  # termynal组件
  - assets/javascripts/termynal.js
  - assets/javascripts/gen_termynal.js

  # 鼠标点击特效
  - https://cdn.jsdelivr.net/gh/TRHX/CDN-for-itrhx.com@3.0.8/js/maodian.js
